name: mova_intelligence_app
description: Приложение MOVA intelligence
version: 1.2.0+1
publish_to: "none"

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.3.7
  go_router: ^16.3.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  meta: ^1.17.0
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  dio: ^5.9.2
  flutter_dotenv: ^6.0.0
  provider: ^6.1.2
  google_mlkit_text_recognition: ^0.15.1
  shared_preferences: ^2.5.4
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  adaptive_icon_background: "#020617"
  adaptive_icon_foreground: assets/icon/app_icon.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/app_icon.png
  branding: assets/splash/brand.png
  android_12:
    color: "#FFFFFF"
    image: assets/icon/app_icon.png
    branding: assets/splash/brand.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/
    - .env